### ISSUE TITLE
[docs] Document export API

### ISSUE THREAD

**Issue by captn3m0** [outline/outline#1000]
Would be nice to have an API that triggers an export of all documents.

Was looking at automating exports as an alternative to #997, but since there is no API, we can't script it.

**Comment by tommoor** [comment]
The endpoint you're looking for is called `collections.exportAll` (there's also an equivalent `collections.export` that takes a `collectionId`) right now it will send an email to the authenticated user with a zip of the documents, this is because the export could take some time and has to be done on a background job.

I'll leave this issue open as a documentation request
