### ISSUE TITLE
Lost Secret Key

### ISSUE THREAD

**Issue by davioliveiira** [outline/outline#1037]
I accidentally lost my secret key on my production server and when I try to use a new secret key it returns error 500 on Google auth. I tried to create a new user and he can't see any collection or documents. Is there any way to reverse this?

Pm2 Logs:

<img width="1025" alt="error" src="https://user-images.githubusercontent.com/5223683/64812289-4fe7ec00-d575-11e9-972b-14f8491f8e38.png">

**Comment by tommoor** [comment]
@davioliveiira the SECRET_KEY encrypts the session tokens and integration keys – the login is failing because the `jwtSecret` field can no longer be decrypted. 

You can either run a script to re-run the `setRandomJwtSecret` method against every user or you can delete all the users from your database. 

Hope this helps
