### ISSUE TITLE
MathJax support

### ISSUE THREAD

**Issue by alichtl** [outline/outline#1038]
My team creates a lot of documentation in a combination of Markdown and LaTex equations. We're very interested in moving to Outline, and support for MathJax would enable us to switch over.

**Comment by tclain** [comment]
> My team creates a lot of documentation in a combination of Markdown and LaTex equations. We're very interested in moving to Outline, and support for MathJax would enable us to switch over.

hi @adamlichtl have you considered mathpix.com ? They have a product (snip) specially tailored for markdown/latex editing and teams support is landing soon (full disclosure, a friend of mine is the CEO). maybe it will be useful as it is specialized for scientific content authoring. 

Still outline is a great product

**Comment by tommoor** [comment]
Totally agree that the rendering should be handled internally, would be very happy to see this functionality added to either Outline itself or the editor project, here: 
https://github.com/outline/rich-markdown-editor

**Comment by hussaini2760** [comment]
Is good to enhance the community with good ideas over a project.

**Comment by controversial** [comment]
Notion uses [KaTeX](https://katex.org/) which renders quickly and synchronously to HTML on the user’s own device (instead of using an external API to render images).

**Comment by tommoor** [comment]
Agreed KaTeX would be a good choice

**Comment by RyanGreenup** [comment]
KaTeX can get annoying because it doesn't support equation numbering, and the non-standard use of `tag` makes converting to LaTeX a headache, having both like [wikiJS](https://docs.requarks.io/releases) makes the most sense.

**Comment by controversial** [comment]
I think for a use case like Outline, where the TeX content would exist in small blocks rather than composing the entire document, these trade-offs would be appropriate. Presenting users with two competing options to accomplish the same thing seems like it would create a much worse experience than would the few edge cases you mentioned.

**Comment by matbrgz** [comment]
Keep it open please;

**Comment by tommoor** [comment]
Note to self – this looks like a great way to implement support relatively quickly:

https://github.com/benrbray/prosemirror-math

**Comment by soulteary** [comment]
We once built an academic community where we needed to show some formulas. Considering the rendering performance of long-form articles, we finally used server-side rendering.  @controversial @tommoor 

In fact, because outline is written by nodejs, this rendering function can be easily migrated into the project.
I have several articles before explaining how to implement a high-performance formula rendering service step by step.

- https://soulteary.com/2021/04/14/use-docker-and-node-to-build-a-formula-rendering-service-part-1.html
- https://soulteary.com/2021/04/15/use-docker-and-node-to-build-a-formula-rendering-service-part-2.html
- https://soulteary.com/2021/04/16/use-docker-and-node-to-build-a-formula-rendering-service-part-3.html

Even if you choose to use front-end scripts for rendering during the input process, you can try to use "pictures/SVG" for rendering when the final rendering is done to avoid the computer fan roar of the viewers.

**Comment by dorianim** [comment]
Any update on this? I'd love to use outline to write down some stuff in university, and this feature is an absolute must-have.

**Comment by frankli0324** [comment]
same looking forward to this feature

**Comment by bouke-sf** [comment]
Would love this as well. Is there a workaround at the moment?

**Comment by realblankname1** [comment]
This would be amazing! Super helpful for using wikis as research pages.

**Comment by TerenceLiu98** [comment]
Is there any update on supporting $\LaTeX$ :)

**Comment by iotatechnology** [comment]
Hi! I'm been using Outline for a year now ... sadly now having to look elsewhere because of the lack of Latex support. Is there any progress or workaround?

**Comment by tommoor** [comment]
Maintainer team is not prioritizing this feature, open to community to implement. The recent integration of Mermaid.js provides a good base

**Comment by iotatechnology** [comment]
Thanks for the feedback.

**Comment by jzmini** [comment]
This feature interests me as well. Could you please let me know how things are going?

**Comment by dsheikh** [comment]
I'm looking forward to #4364 being merged! That would 100% sell me on Outline.
