### ISSUE TITLE
mailto: links don't work

### ISSUE THREAD

**Issue by captn3m0** [outline/outline#1090]
1. Edit a document
2. Create a link
3. Use a mailto: link as the target
4. Click Publish

The link changes to `https://mailto:` instead.

**Comment by TommyJackson85** [comment]
If this would be a good first issue, I am interested in attempting to fix it or help out, as my first contribution to Outline.

**Comment by tommoor** [comment]
Hi @TommyJackson85 I think this is likely to be a good first issue tea, the fix itself likely lies in the submodule for the editor: https://github.com/outline/rich-markdown-editor

**Comment by TommyJackson85** [comment]
@tommoor Let me try to fix it. It might take me a while to understand the repository a bit more as I only recently found it but I am happy to try.

**Comment by TommyJackson85** [comment]
From the LinkToolbar.js file in rich-markdown-editor repository, I managed to fix this in development through a conditional statement in the the save function.

`save = (href: string) => {
    const { editor, link } = this.props;
    href = href.trim();

    if (href) {
      //If the input starts with 'mailto:', keep it the same.
      // If the input doesn't start with protocol or relative slash, make sure
      // a protocol is added
      if (href.startsWith("mailto:")) {
        href;
      } else if (!href.startsWith("/") && !href.match(/^https?:\/\//i)) {
        href = `https://${href}`;
      }
      editor.setNodeByKey(link.key, { type: "link", data: { href } });
    } else if (link) {
      editor.unwrapInlineByKey(link.key);
    }
    editor.deselect();
    this.props.onBlur();
  };
`

I kept it in a separate condition to keep it clean. I am open to other suggestions.
If I am to make a commit on this repository, I may need to be given permissions to do so. If somebody can help me with this, it would be great. :) I will commit to a separate branch if I need to. I also don't know how to move this issue to In Progress.

Also, would it make more sense to move this issue to the rich-markdown-editor repository instead of the main outline repository?

**Comment by tommoor** [comment]
Hey @TommyJackson85 – you should fork the repository and put in a pull request. GitHub has good help docs on how to contribute here:

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

No need to move the issue between repositories!

**Comment by TommyJackson85** [comment]
I forked and made my pull request:

https://github.com/outline/rich-markdown-editor/pull/132

I made a slight change to link.js file accidentally but code is not affected. I wouldn't of pushed it if was dangerous but I'll becareful next time! :)
I've also accidentally added a package-lock.json file. Unsure if this is a severe issue or if it needs to be there. 

Test files may need to be updated for my change to new code, if it exist.

**Comment by TommyJackson85** [comment]
@tommoor is it possible to reopen pull request [fix: Issue outline/outline#1090: Removed adding of https protocols when creating mailto links from link toolbar. #132](https://github.com/outline/rich-markdown-editor/pull/132)?

I reopened my branch to push new changes, to prevent https adding to other protocols.
