### ISSUE TITLE
Can't write wiki in Chinese

### ISSUE THREAD

**Issue by pengzihe** [outline/outline#1180]
Hi,
When I write WIKI in Chinese, it doesn't work, letters always appear, version numbers are V0.38.1 and V0.40.0. Please help to fix it.
![image](https://user-images.githubusercontent.com/10286479/75024416-4d9a9e00-54d4-11ea-968f-cd96fafc2e7d.png)

**Comment by tommoor** [comment]
Hey, thanks for reporting – we're already tracking this issue here (#1027) – work is ongoing to upgrade the editor to support soft keyboards, unfortunately it has required a total rebuild, i'd imagine there is at least a few weeks perhaps a month of work left.

You can follow progress here:
https://github.com/outline/rich-markdown-editor/pull/150
