### ISSUE TITLE
Don't Outline have sub collection?

### ISSUE THREAD

**Issue by wisoez** [outline/outline#1201]
Hi there,
Can you tell me how to create sub-collection? and how can i move the document to the other collection?
Thank!!!

**Comment by tommoor** [comment]
Hey, currently there are just collections at the top level and documents below that – documents can be nested and will automatically display an index of their nested documents so this acts very similar to a sub-collection except you can also add your own text.

TLDR: Create documents and nest them instead!

**Comment by Darlelet** [comment]
Sad thing is that there is no way to apply specific permissions (group or individual) to documents / nested documents.
Permissions are only available to top level collections.

**Comment by bhanuc** [comment]
are there plans on work on this in future, this seems like an essential feature missing right now from outline- I can contribute code if required @tommoor

**Comment by JulianForster01** [comment]
Hi,
i think that would be great too. Are there any plans on implementing this feature @tommoor ?

I can cantribute code too. The biggest questions for me is, if adding subcollections are better or adding permissions to single documents.
Both solutions have their advantages but i think adding subcollections would be a little more cleaner and organized?
We can serialize them into folders if the user wants to export them.

**Comment by dolsem** [comment]
@tommoor I am faced with the same issue: I need fine-grained permissions and I need to either be able to add users/groups to individual documents, or create a collection for almost every document I have, but in that case I need to group them because having everything at the top level is a nightmare. It seems like the first approach has a bigger implementational hurdle, so how about adding folders for collections?

**Comment by dolsem** [comment]
I pushed a PR for document-level permissions: https://github.com/outline/outline/pull/4258
