### ISSUE TITLE
Japanese input is totally broken

### ISSUE THREAD

**Issue by gunta** [outline/outline#1235]
Thanks for making outline.

Input is broken probably not only Japanese but anything that uses an IME.
Right now it is unusable.

Tested on macOS Catalina.
On Safari it's 200% broken.
On Chrome it's 100% broken.

**Comment by tommoor** [comment]
Yes, unfortunately we're aware – this is a bug in the underlying framework we used to build the text editor, I've been combining these issues here: https://github.com/outline/outline/issues/1027

Work is underway to rebuild the text editor which will resolve the issue here: https://github.com/outline/outline/pull/1227

It's basically like doing a heart transplant while the patient is running 😆
