### ISSUE TITLE
No support for different Internal S3 URL

### ISSUE THREAD

**Issue by TeNNoX** [outline/outline#1296]
When you host the S3ish (e.g. minio) next to outline, you need to access it via a local URL (at least in my setup): `http://minio:9000/` - but changing the `AWS_S3_UPLOAD_BUCKET_URL` would break the frontend.

How about adding an optional `AWS_S3_UPLOAD_BUCKET_URL_INTERNAL` that allows to override?

This would also remove the need for the weird hardcoded replacement for the docker setup.

**Comment by tommoor** [comment]
I don't think this is additional complication that we want to introduce as you can just use a hostname that is accessible to both the frontend and the backend.

**Comment by TeNNoX** [comment]
... which already is not the case in the local development setup, that's why you did the hardcoded check - which, by the way, caused some problems for me when I used `s3` as the docker-compose name on my production setup, as suddenly the production setup changed the URLs to `localhost`...

I see that it's not a thing that a *good* setup would need, but unfortunately we would need to hardcode a static IP for our docker-compose / traefik setup, as unfortunately it doesn't route internal requests to the reverse proxy correctly.

If you won't add it, we need to maintain our own fork - but I would understand, and obviously not hold it against you in any way. :wink: 
Feel free to close the PR in that case.

**Comment by TeNNoX** [comment]
I also think it would improve things for other setups, as the e.g. Minio instance wouldn't need to be accessed via the reverse proxy - but you can give outline the internal URL.

**Comment by tommoor** [comment]
> which already is not the case in the local development setup, that's why you did the hardcoded check

It's true, this was the case although recently the local dev setup changed so that the node portion runs outside of docker and technically this isn't needed any more. I kept it in for backwards compatibility for a little while, but it can be removed.


> we would need to hardcode a static IP for our docker-compose / traefik setup, as unfortunately it doesn't route internal requests to the reverse proxy correctly.

Yes, unfortunately this shortcoming of your particular setup isn't something we should maintain code complexity for in the OSS project, there are thousands of companies hosting Outline and this is the first time it's been brought up. It seems like you understand 😄

**Comment by TeNNoX** [comment]
Thanks for considering.
& Thanks for your work!
