### ISSUE TITLE
Ability to Add Custom Fields to Profile

### ISSUE THREAD

**Issue by matbrgz** [outline/outline#1327]
This feature would be very interesting so as we manage large teams within the platform, we would like to be able to add new fields to the user's profile. It would be amazing to be able to customize this through the interface, but if it is not possible for now at least some fields.

![image](https://user-images.githubusercontent.com/23284276/86270828-40886c80-bba2-11ea-9bf3-88c62d1f798f.png)

**Comment by tommoor** [comment]
Open to this idea, I don't think the core maintainer team will have time in the near future to implement though.

One thing we could also do is pull the custom fields across from Slack when signing in with that method.

**Comment by thenanyu** [comment]
how about giving everyone a free-form bio document attached to their user account? Teams can enforce whatever internal rules they want through an example doc

**Comment by MatheusRV** [comment]
I understand that it is not a priority, we can continue this issue here. I imagine that the Administrator can dynamically institute the fields (same as in the slack) and users can complement; That is, an administrator defines what are the fields and users can fill in, I imagine that this has a technical debt, that I would like your help to fill in with the largest amount of information so that we can implement this as a PR.

**Comment by MatheusRV** [comment]
Tom could you rename this for something related to "One thing we could also do is pull the custom fields across from Slack when signing in with that method.". I think that receive data from slack could resolve for me.

**Comment by matbrgz** [comment]
Still need it.

**Comment by matbrgz** [comment]
@tommoor could you please reopen it?

@iamsaumya are you interested in a bounty to do that?

@thenanyu could you please help us with the design (& requirements)?
