### ISSUE TITLE
Show documents in trash when deleting a collection

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1341]
**To Reproduce**
1. Delete a Collection

**Expected behavior**
Recover deleted collection, or at least the documents inside collection in trash. 

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.43.3

**Comment by tommoor** [comment]
Collections have never gone to trash, we don't really have a display for that and the delete screen is very clear that deleting a collection is permanent. Totally agree that the documents within should go to trash though, that would be a good improvement.

I guess the question is what happens if you restore a document and it's containing collection has been deleted 🤔
