### ISSUE TITLE
Email Bug on Production but not on development

### ISSUE THREAD

**Issue by chsasank** [outline/outline#1380]
**To Reproduce**
1. Invite people to email authentication

On `yarn dev` emails gets sent. But on production, I get the following error and email is not sent:

```
outline_1  | (node:126) UnhandledPromiseRejectionWarning: Error: 140545354009928:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
outline_1  |
outline_1  | (node:126) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
outline_1  | (node:126) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**
A email sent to the requested email.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
<img width="891" alt="image" src="https://user-images.githubusercontent.com/9305875/88136129-4227dc00-cc06-11ea-9e30-c487106fd45b.png">

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.45.0

**Comment by tommoor** [comment]
Hi @chsasank – I've never seen this error, clearly it's something to do with the openssl setup in your production environment. I don't think this is likely to be anything related to the Outline codebase.

**Comment by chsasank** [comment]
But I'm using [outline's docker from dockerhub](https://hub.docker.com/r/outlinewiki/outline).

My docker-compose setup is here if you want to look: https://github.com/chsasank/outline-wiki-docker-compose

What's perplexing is the email works on dev build but on production build.

**Comment by tommoor** [comment]
It's probably the SMTP server configuration, according to Google search "This error usually occurs if you attempt to connect to something that isn't using SSL/TLS".

**Comment by chsasank** [comment]
Wonder why it's not throwing out this error on dev build. Will help me get to the root of the problem. Will contribute back to outline if it's something that could be fixed.

**Comment by jens108** [comment]
Any idea what might be causing this? I am getting the same error, and already tried using other SMTP-servers as standin (Google, web.de, my own). Right now nobody can login to our Outline page. It's also self-hosted via docker, running version 0.50

**Comment by tommoor** [comment]
Are you sure is the same error with open SSL￼? That seems incredibly unlikely considering the docker image is fixed.

**Comment by chsasank** [comment]
Please check https://github.com/chsasank/outline-wiki-docker-compose/issues/12 and https://kevalnagda.github.io/sendgrid-with-outline on how we solved this.

**Comment by jens108** [comment]
Hey, thanks for the quick reactions! 

- Yes @tommoor it's the exact same error as mentioned in the original post. I tried around a bit -- sometimes I get the error above, and sometimes my SMTP_HOST is swapped with 127.0.0.1, which then fails because the SMTP server is not in the same docker container as Outline.
- Our email setup used to work, then I updated from 0.47 to 0.50 and now it doesn't work any more with the same environment settings. At first there were some bugs all over the place after the update (i.e. my account wasn't shown the admin options), but I was able to fix that with `yarn sequelize:migrate`. All that's left is email.
- The SMTP server is used by other docker images (e.g. owncloud) with the same settings for SMTP emails, which all work fine.
- Thanks for the link @chsasank. I think that TLS workaround would need to be applied after every update, right? 

I since got it to work with another service like sendgrid (web.de), but emails are still spotty. Sometimes they get sent, sometimes they don't. Sometimes nothing happens when you click "Send link" in Outline and then it works again after a minute.

**Comment by svallory** [comment]
@jens108 and anyone using GApps or Gmail: you need to use port 465 instead of 587

**Comment by MetaBliss** [comment]
Hi @svallory thanks for your message. What would the SMTP_TLS_CIPHERS value be? I noticed that in the outline .env file but was not sure what value to put there. I would be using gmail.

**Comment by svallory** [comment]
@MetaBliss sorry for the delayed response. I did not set that env var

**Comment by Sleepful** [comment]
I had this issue because I was using port 587 which implies STARTTLS, per this other issue, Outline does not support STARTTLS https://github.com/outline/outline/discussions/2343#discussioncomment-1026572

Hopefully this gets looked at because some providers only offer STARTTLS 🤷
