### ISSUE TITLE
Error socketOnEnd(_http_server)

### ISSUE THREAD

**Issue by MatheusRV** [outline/outline#1497]
```
Error: Parse Error
  File "_http_server.js", line 539, col 22, in socketOnEnd
  File "events.js", line 327, col 22, in Socket.emit
  File "domain.js", line 483, col 12, in Socket.EventEmitter.emit
  File "_stream_readable.js", line 1220, col 12, in endReadableNT
  File "internal/process/task_queues.js", line 84, col 21, in processTicksAndRejections
```

**To Reproduce**
1. Install Sentry
2. Wait

**Expected behavior**
No Error

**Screenshots**
![image](https://user-images.githubusercontent.com/23284276/91556778-a6c30e80-e909-11ea-875e-5fa64310f26c.png)

**Outline (please complete the following information):**
- Install: Self Hosted
- Version: 0.46.0

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/23284276/91556849-ca865480-e909-11ea-898c-b7038b79c0fa.png)

**Comment by tommoor** [comment]
In Sentry you should see `handled=yes` which means the error was correctly handled on the server. This is due to the client terminating the connection before the request is complete, something that can always happen and we can't do anything about 👍 

![image](https://user-images.githubusercontent.com/380914/92412476-dd1a3e00-f100-11ea-96b2-5f2ffe19e8d4.png)
