### ISSUE TITLE
starring from context menu leaves behind active state and does not dismiss menu

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#1656]
close this issue if this is desired behavior. but it felt a bit unexpected.
- closing the menu after a click would be natural
- not leaving behind an active state on the menu item would also be ok, if toggling isn't meant to dismiss the menu

it's the combination of both that doesn't feel quite natural

![image](https://user-images.githubusercontent.com/427579/99193622-1a1d3500-272f-11eb-88d7-f222117a0781.png)

**Comment by tommoor** [comment]
The menu is purposefully kept open right now – the reason is because there is nowhere else that gives feedback that the star was successful, if you're viewing the document then the starred state isn't actually shown anywhere 🙈 

I'd like to add the ability to star into the header next to the document title? The menu could then be restored to normal behavior and might be the best way to resolve this.

**Comment by tommoor** [comment]
This has been addressed with the context menu rebuild
