### ISSUE TITLE
Read-only users

### ISSUE THREAD

**Issue by tommoor** [outline/outline#1873]
We'd like to add the ability to have read-only users, currently the option exists on a per-collection basis however there is a need to also optionally have this ability at the user-level.

### Requirements

- A new database column `isViewer`
- A new control on `settings -> people -> user menu` to change user to a viewer or back to a regular member.
- Must have a confirmation dialog for this operation
- Viewers do not have the ability to modify anything except their own profile

**Comment by iamsaumya** [comment]
I will work on this feature. Thanks!

**Comment by iamsaumya** [comment]
@tommoor 
I think we just have to update the policies appropriately as everything in frontend is already at place.

However, I am not sure how to handle `Attachment` policies. Here is what I believe will be ideal approach:

1. Attachment `create` should not be accesible.
2. Attachment `read` should be accessible but not `delete`. Right now `read` and `delete` are coupled together in a policy. The way I see it, we will have to decouple it and make `delete` inaccessible. 

Also, I see `pin` and `unpin` policies for document. Is there a way to pin document in the app :thinking: ?  

PS: I know you are extremely busy, tagged you so that the doubts are resolved at the earliest and I can keep going. :sweat_smile:

**Comment by tommoor** [comment]
> The way I see it, we will have to decouple it and make delete inaccessible.

Sounds right 👍 

> Also, I see pin and unpin policies for document. Is there a way to pin document in the app 🤔 ?

Yea, you can "pin" a document within a collection which keeps it at the top.

**Comment by iamsaumya** [comment]
I'm sorry I just can't find the option. Could you please navigate me to it?

**Comment by tommoor** [comment]
It's only available in the "..." menu on a document in a collection right now, quite hidden I guess :)

**Comment by iamsaumya** [comment]
I still can't find it :cry:

![Screenshot from 2021-03-11 02-53-39](https://user-images.githubusercontent.com/40148448/110699587-084b2a80-8215-11eb-8be8-da19c1eb4a79.png)

**Comment by tommoor** [comment]
It's only available from the screen where it actually has a visible effect - thinking was otherwise you could toggle it on documents and have no idea what was happening.

![image](https://user-images.githubusercontent.com/380914/110703422-9b9a4680-81a8-11eb-8c79-01143783c613.png)

**Comment by iamsaumya** [comment]
Actually, I did not know this page existed :open_mouth:
