### ISSUE TITLE
Warning when dragging document between collections with different user permissions

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2150]
When moving a document today it just happens immediately, It would be nice if when moving a document from a collection with limited access to another with different access we would show a confirmation dialog that the user intended to change the permission level.

**Comment by iamsaumya** [comment]
If I speak for myself, I will not want obstructions when I drag and drop something. The experience should be fluid. 

Suggestions - We can show a warning toast, assuming that undo toast for a dropped document is already implemented before this enhancement. Cohesively, both the toast can do the work. 

If we go with a confirmation dialog, we should not show the undo toast because it will be weird to have an undo toast when you confirm that you want to drop.

**Comment by tommoor** [comment]
I think this would be tough to explain in a toast but I understand wanting the action to be fluid. I'm imagining this would only show up if the permission level is going from private -> team accessible which should be a small subset of the time

**Comment by iamsaumya** [comment]
> if the permission level is going from private -> team
Noted.
