### ISSUE TITLE
Investigate docker-compatible plugin architecture 

### ISSUE THREAD

**Issue by tommoor** [outline/outline#2219]
I'm looking for examples of applications that are deployed via docker and allow for plugins, either through:

- a "store" that they are downloaded from directly into the container storage 
- co-locating plugin code alongside the container and loading dynamically
- something else?

If you know of anything similar please post here.

**Comment by ChetanGoti** [comment]
- [Grafana](https://grafana.com/docs/grafana/latest/installation/docker/#install-plugins-in-the-docker-container)
- [Kibana](https://www.elastic.co/guide/en/cloud-enterprise/current/ece-include-additional-kibana-plugin.html#ece-create-modified-docker-image) 
- [docker-library Wordpress](https://github.com/docker-library/docs/tree/master/wordpress#include-pre-installed-themes--plugins)

They all support pre-installed plugins from any sources as well as installing at run-time later by installing in container.

**Comment by almereyda** [comment]
From the Docker (Compose) point of view, we know two different kinds of volumes:

1. the Container filesystem
2. other overlay filesystems provided by storage drivers, or host-mapped directories

Both can be used for storing application state, and bring different caveats:

- Grafana installs the plugins to the application container at runtime, which will have to be done again with every update of the base image, optionally allowing to include them at build time
- Kibana installs the plugins to the application container at build time, which is harder to customise, but can be preloaded for Containers in image registries.
- WordPress considers the plugins a side-effect and handles their state and thus versions independently within a dedicated storage volume, e.g. a host-mapped directory, and loads them from there. This comes with extra precautions for file and directory ownership and permissions, since they need to map from the host/storage-volume-provider into the container.

As a Node.js examples I can mention Federated Wiki and Etherpad, which both use npm as the plugin registry and load packages within their `node_modules` directory from the `wiki-plugin-` and `ep_` namespaces upon startup.

In both of their cases, plugins are "burnt" into the image at compile time:

- https://github.com/ether/etherpad-lite/commit/4582f9daebce59fec4000db38651b8c6ae32ebba
- https://github.com/federated-wiki/wiki-docker-plugins/blob/master/Dockerfile

There is also an example for Federated Wiki how to npm link Node modules within the Container, in so additional state from outside can be reused within:

- https://github.com/dobbs/wiki-tls/blob/master/migrations/2019-03-11-setup-local-plugin-development
- https://github.com/dobbs/wiki-tls/blob/master/docker-compose.override.yml#L6

Therefore the choice how to provide plugins within a Docker environment heavily depends on the deployment scenario, and can be less tightly coupled at runtime for local development environments, and might be accounted for at build time for optimised production environments.
