### ISSUE TITLE
Exported Markdown file contains "random" slashes

### ISSUE THREAD

**Issue by syphernl** [outline/outline#2587]
When exporting a file to Markdown I see a lot of "random" slashes all over the place. 
They probably come from `\n` or `\r`, but are somehow not being replaced properly when exporting to Markdown.

**To Reproduce**
1. Make a list with hard newlines like so:
   ````markdown
   * First line

   * Second Line

   * Third Line
   ````
2. Click on 'Export'
3. See that file contains slashes in between:
   ```markdown
   * First line
   
     \
   * Second Line
   
     \
   * Third Line

   ```

This also happens with the files in the "Collection export".

**Expected behavior**
No "random" slashes in the export

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**
- Install: self-hosted
- Version: v.0.59.0

**Comment by tommoor** [comment]
The slashes represent blank lines and are there so that re-importing the document into another Outline instance would retain the same layout. Ideally we need to have some options as part of the export process to potentially "clean up" the output – is what happens when you use the "Download" option on an individual document, for example.
