### ISSUE TITLE
Checklist items cannot be changed if Bitwarden browser extension is installed

### ISSUE THREAD

**Issue by razor950** [outline/outline#2921]
I am on Windows 10 and neither Firefox or Vivaldi allow me to use the checkboxes whereas Chrome and Edge work fine.
Vivaldi uses Chrome's backend so I am a bit confused there.

**Comment by tommoor** [comment]
It was recently mentioned that Bitwarden was breaking this functionality for a user, could that be the case here?

**Comment by mwegner** [comment]
Not OP, but I came to the issues page to see if there were reports of Firefox not working with checklists.  It worked in Safari for me, but I keep Safari essentially default.

Turns out the difference was Bitwarden!  You can add your URL to the extension's Settings -> Excluded Domains list (this is for a self-hosted Outline instance).

I didn't notice anything weird in the console when trying to figure out what was going wrong, but I didn't spend very long trying to debug it before checking here.

**Comment by razor950** [comment]
I am speechless, I should've tried the site without any extensions on but I did not. The issue is fixed when you exclude the domain but am super curious to know why it happens but at least its fully working now :)

**Comment by tommoor** [comment]
I've tracked it down – I don't think it's Outline's _fault_ per-say, but we can work around it by making the checkboxes not real inputs

**Comment by oakbrad** [comment]
I can check task boxes off with Bitwarden in Firefox if I disable collaborative editing. If collaborative editing is enabled, I have the same issue with tasks being unresponsive.
