### ISSUE TITLE
French translation of “You” + “updated” should be improved

### ISSUE THREAD

**Issue by alexislefebvre** [outline/outline#2955]
**To Reproduce**

1.Edit and save a document
2. See “You updated 1 minute ago”
3. Switch to French language
4. See “Vous mis à jour il y a 1 minute”

**Expected behavior**

“Vous mis à jour …” is not correct, it should be something like “Vous **avez** mis à jour …”.

The translations are good, but when they use “You” + “updated”, the result in French is not good. Updating “updated” in French would not work because it needs another translation when another user updates a page.

Possible solution: use complete strings to translate instead of chunks: “You updated” instead of “You” + “updated”.

**Outline:**
- Install: self hosted
- Version: 0.61.1

**Desktop:**
 - OS: Linux Ubuntu
 - Browser Firefox
 - Version 96.0

**Comment by Limezy** [comment]
I'm currently trying to solve that issue, which is indeed a problem for French users like me.

After a bit of digging into the code, I think the problem is around here : https://github.com/outline/outline/blob/1b913054e8ecdc542f4988d84d445bb9db54bbd1/app/components/DocumentMeta.tsx#L146

For the French output to be correct : 
* If lastUpdatedByCurrentUser is true, I would need to create a new translation string, which would be "you" in English, but "Vous avez" (=you have...) in French. The final sentence should be "Vous avez supprimé / archivé / créé / publié / enregistré / mis à jour..."
* If that boolean is false, I would need to add a translation string, which would be void in English, but which would look like "{{ updatedBy.name }} a" (=updatedBy.name has...). The final sentence should be "NAME a supprimé / archivé / créé / publié / enregistré / mis à jour..."

@tommoor how could I create : 
* A translation string which is the same as the already existing "you" in English but that has another translation ? Can I create for instance "You [have]" which translates to "You" in English and "Vous avez" in French ?
* A translation string which is void in English but has a translation in other languages ? Can I create for instance "{{ updatedBy.name }} [has]" which translates to "{{ updatedBy.name }}" in English and "{{ updatedBy.name }} a" in French ?

Thanks !

**Comment by tommoor** [comment]
The best way would be to convert all of these lines:

https://github.com/outline/outline/blob/1b913054e8ecdc542f4988d84d445bb9db54bbd1/app/components/DocumentMeta.tsx#L81

into ternaries with the you-case separated, for example:

```typescript
{lastUpdatedByCurrentUser ? t("You deleted") : <>{userName} {t("deleted")}</>} <Time dateTime={deletedAt} addSuffix />
```

For more accurate translation we could do string interpolation, this will lose the existing translations but be more accurate in the long run:

```typescript
{lastUpdatedByCurrentUser ? t("You deleted") : t("{{ userName}} deleted", { userName })} <Time dateTime={deletedAt} addSuffix />
```

**Comment by Limezy** [comment]
I'll try a first PR. OK for you if I use your second option that you seem to prefer ?
Are the new translation strings generated automatically from the code ?

**Comment by tommoor** [comment]
Sounds good, and yes the strings are generated on commit.

**Comment by Limezy** [comment]
I guess that issue could be closed !
