### ISSUE TITLE
sidebar trigger swallows mouse events when content area is narrow

### ISSUE THREAD

**Issue by thenanyu** [outline/outline#3009]
when the content is very close to the sidebar threshold, it's impossible to activate clickable elements like the expand-collapse control on headings or the drag handle on list items.

![image](https://user-images.githubusercontent.com/427579/151281038-59bd89e7-19fa-42d4-ae14-a3eed59012f3.png)

**Comment by tommoor** [comment]
Any suggestions for whoever fixes this? Just that the click area for collapse is moved behind the doc content?

**Comment by ig505gi** [comment]
> 

Hey! I am new to the codebase still exploring the functionality! I would like to work on this issue as my first issue on github. Can I try it? I think moving click area behind the doc content is OK. Although we can't click to expend sidebar in this situation, we can move the cursor to left edge of screen in order to expend sidebar. The other idea is that increasing the margin between sidebar threshold and the doc content. Maybe it will affect the proper layout of this html. Which solution do you prefer? Or other ideas?

**Comment by ig505gi** [comment]
> Any suggestions for whoever fixes this? Just that the click area for collapse is moved behind the doc content?

Hey! I am new to the codebase still exploring the functionality! I would like to work on this issue as my first issue on github. Can I try it? I think moving click area behind the doc content is OK. Although we can't click to expand sidebar in this situation, we can move the cursor to left edge of screen in order to expand sidebar. The other idea is that increasing the margin between sidebar threshold and the doc content. Maybe it will affect the proper layout of this html. Which solution do you prefer? Or other ideas?
