### ISSUE TITLE
Editing information loss. "document has changed since last revision outline issue"

### ISSUE THREAD

**Issue by victordariovera** [outline/outline#3157]
When I'm editing a document for more that 2 minutes and I try to save it, "document has changed since last revision" message appears and it's no possible to save the document with the save butto. When I reload the browser to exit that situation all the changes was lost.

**To Reproduce**
1. Create new nested document or edit an existing one
2. Edit the document for more that 2 minutes
3. Try to save manually, then the message "document has changed since last revision" appears. Saving its not possible
4. When refresh the browser o re-open document all changes was lost

**Expected behavior**
Changes saved

**Outline (please complete the following information):**
- Install: selfhosted
- Version: v0.61.1 , I'm using docker image outlinewiki/outline:latest

**Comment by victordariovera** [comment]
Rollback to DockerHub image tagged outlinewiki/outline:0.60.3 seems to be ok.

**Comment by tommoor** [comment]
This has been addressed on `main` and a fix will be in the next release

**Comment by goodnull** [comment]
> This has been addressed on `main` and a fix will be in the next release

Version 0.66.3 encountered this problem

/api/documents.update

{"ok":false,"error":"invalid_request","status":400,"message":"Document has changed since last revision"}

**Comment by ve7mjc** [comment]
Experiencing this problem in 0.68.1.

I am not sure if it is related but when I create a new document (in particular, a nested doc) and begin typing the document title, it takes me about 30 seconds of typing letter by letter as the UI hangs with each keypress. I observe "[Violation] 'input' handler took 1162ms" in the browser dev console for every character I type. Lately I have been typing out titles in notepad and then pasting it into Outline to save time.

FWIW, every character I type into the input field of the document title results in actual network traffic to the backend. The same goes for simply hovering my mouse down the left side of the navigation bar. As I drag it over collections with nested documents, it results in a flurry of network requests and my UI begins to lag.

Then, after trying to publish the document I get the Error 400 "invalid_request"; "document has changed since last revision". I then copy all of my typed content to clipboard, instruct the browser to "reload", hit edit, and then paste my document content back in and hit publish.

Quite a few workarounds I am having to do throughout the day to even use this wiki. I would happily narrow this down and provide specifics if I knew where to start.

**Comment by tommoor** [comment]
You can profile the application - developer tools inspector -> performance. Record the profiling information while you type and then export and upload here, we can debug then. This isn't something that has been reported elsewhere so likely some sort of issue with your installation.

**Comment by 98h398hrpohpoai** [comment]
I'm noticing this behavior as well as 0.68.1.
Every time I publish a new document it immediately goes into "Document has changed since last revision" and doesn't save the content of the document (only the title).
Upon reloading the document is seems to work fine.
So far testing doesn't seem to affect creating a draft and then publishing (though I haven't tested much).
