### ISSUE TITLE
Make the collection and document expansion a smooth experience  

### ISSUE THREAD

**Issue by iamsaumya** [outline/outline#3167]
Clicking on disclosures shouldn't just display all the nested items. It should do it with some smoothness.

@thenanyu, Could you please list the transition issues you had encountered in #3102 for various devices?

**Comment by tommoor** [comment]
Definitely open to experimentation but I think we want to keep the collapse expand "snappy" here.

**Comment by thenanyu** [comment]
@iamsaumya — The biggest issues that I encountered from what I remember 

1. using `overflow: hidden` for the show/hide children requires that everything is rendered ahead of time, which create *a lot* of renders. You can see some of the discussion we had on the PR to mitigate this
2. using `overflow: hidden` makes the focus state (via the TAB key) get cut off. This might be fixed because of the new way the folders are designed

minor issues

1. the expand/collapse animation wasn't used in all of the sections (starred heading, collections heading)
2. the timing was a bit too slow and uncoordinated with the disclosure animation (this is solvable with some amount of fiddling)
