### ISSUE TITLE
Export does not contain Collection Description

### ISSUE THREAD

**Issue by 0ff** [outline/outline#3189]
When exporting a collection (or all collections), collection descriptions are not exported.

**To Reproduce**
1. Create a Collection
2. Set a description on the collection
3. Export that collection as zip

**Expected behavior**
The collection's description should be part of the export archive, but it is not.

**Outline (please complete the following information):**
- Install: getoutline.com

**Comment by Limezy** [comment]
I would add that when importing back into another instance, the icon and the color of that collection are lost !

**Comment by tommoor** [comment]
Both of these are expected right now, only document related data is exported

**Comment by markive** [comment]
This is what I am looking for.. If my business is building all of our knowledge into Outline and we are hosting with you for convenience we need to know that if you were to stop supporting outline we can at least choose to self-host. 

Being open-source is great, but in order to choose hosting with you, I need to know that in case that needed to end, either for our internal reasons or because that option is ending, that we can fully export <> import between environments.

I don't mind setting up users or basic configuration again.. But in my test, I cannot get the same structure to exactly import back which is worrying.
