### ISSUE TITLE
image resized doesn't work anymore

### ISSUE THREAD

**Issue by JoaoNetoUello** [outline/outline#3248]
I realized that when I paste a image on article the image isn't resized anymore, But it worked a week ago, is that a bug?

**Comment by warnus** [comment]
Oh.. I didn't know outline wiki support resize image. Because resize image didn't work.

Maybe, this is help explain the problem.

<img width="323" alt="test_image" src="https://user-images.githubusercontent.com/5237424/159482939-d5ea7ab9-6f2b-4999-a698-53f0d177339c.png">

When I upload image and choose the image, nothing show up to resize image.

I use outline wiki v0.62.0. There was probem on v0.61.0 as well.

My system environment

OS : Ubuntu 20.04
Web Server : nginx
S3 : minio
Browser : Chrome
