### ISSUE TITLE
Allow image resizing

### ISSUE THREAD

**Issue by tommoor** [outline/outline#3329]
### Discussed in https://github.com/outline/outline/discussions/1369

<div type='discussions-op-text'>

<sup>Originally posted by **arpitchaudhari** July 18, 2020</sup>
I am writing a doc but unable to resize the image. It would be nice if we can resize images in outline. 

![Screenshot 2020-07-19 at 10 25 14 AM](https://user-images.githubusercontent.com/29978858/87867458-7a32e300-c9aa-11ea-9883-f344f38d52d5.png)
</div>

**Comment by mdow09** [comment]
![EmsSdPOteH](https://user-images.githubusercontent.com/63035339/167502811-0e3578ff-240e-4d0a-96ed-99c674c24093.png)

I also have this issue. It is very awkward to only have left, right, or center alignment with this type of image because I am unable to write below it with pressing lots of carriage returns to get below it. The image is huge on the page. I'd much rather it be able to be resizable or click-to-zoomed.

**Comment by not7cd** [comment]
This thread shows different implementations of this feature in markdown. 
https://stackoverflow.com/questions/14675913/changing-image-size-in-markdown
