### ISSUE TITLE
Sometimes private collections are visible to admins 

### ISSUE THREAD

**Issue by gemathus** [outline/outline#3454]
I've experienced this issue twice: a non admin user creates a collection and removes read and write access to all (making the collection private). Now, me, as an admin user, logged into our self deployed Outline and was able to see this user's private collection and documents. After refreshing the page, the collection was no longer visible to me. 

**To Reproduce**
I don't know yet... We've only experienced this issue twice in the last month without any clear reproduction steps. I will keep a look out in our dev environment to try to catch it in the logs. 

**Expected behavior**
Private documents should not be visible to anyone, including admin users.

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.63.0

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 100.0.4896.127 (Official Build) (arm64)

**Comment by tommoor** [comment]
It was recently changed so that admins have read permissions to collections if the id is known, so I suspect this is related – although it is indicative of a possible wider bug where permissions are not correctly propagated perhaps? 

Ideally we'd allow admins to see the existence and manage private collections but not read the content without being added explicitly as a member either by themselves or someone else. This will mean separating the permission that currently encompasses both.

**Comment by gemathus** [comment]
Right, I had noticed that read access was granted to admins given the full url. Nonetheless, this happened while I was in another document/collection, and I had not previously accessed this private collection, it just showed up on my sidebar. 

I will try to reproduce this in the next couple of days, and keep you posted.

**Comment by thumDer** [comment]
Also, if there is a collection with view-only default permission, I can edit its pages, even if I don't have explicit edit permission. It is a bit inconsistent. However, as an admin, there are cases where I wan't to see all of the collections (even private ones).
