### ISSUE TITLE
Link to nested document should display a preview when hovering in the shared url

### ISSUE THREAD

**Issue by Limezy** [outline/outline#3469]
**To Reproduce**
1. Publish a main document
2. Publish a nested document inside the main document
3. Add a link to the nested document inside the main document
4. When hovering over the link, a preview of the nested document is shown
5. Share your main document on internet, and activate the "publish nested documents" option
6. Visitors reading your main document won't have the preview of the nested document when hovering on the link

**Expected behavior**
A preview of nested document should be shown when hovering on the link

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.63.0

**Comment by kingfungdesign** [comment]
![msedge_Y6Wl2OXcoN](https://user-images.githubusercontent.com/52369186/216367612-635a6dd4-26dc-4857-bfee-2d522bb5b42b.gif)
![msedge_908XrTA0Ws](https://user-images.githubusercontent.com/52369186/216367639-796979c7-b979-4e04-9c59-ee4a9c59194c.gif)
I suppose this is what this issue is about. This is something I think the viewers of the publicly shared documents would greatly appreciate. I would want the viewers that I share my knowledge to have the closest browsing experience as I do. I think it'd be a shame if they don't find browsing Outline documents as enjoyable as I know it could be.
