### ISSUE TITLE
Cannot turn off collaborative editing

### ISSUE THREAD

**Issue by jonatcb** [outline/outline#3488]
Maybe a known thing, and I'm wondering if I can't disable because users are currently editing -- but I'm not able to turn off collaborative editing since I've turned it on. Have tried this from two browsers (Opera, Safari) to no avail.

Thanks for any help!
Jonathan

PS
I like the feature, but we would prefer to have an edit button even in collaborative editing mode, as described in this ticket:   https://github.com/outline/outline/issues/3132

**Comment by Limezy** [comment]
It's "by design" as if you turn it off you may have data loss.
It's true that having a toggle switch is a little bit misleading though... 
Collaborative editing will probably be "forced" on the next Outline releases so the best is probably to stick to it. If you really need to turn it back off and can accept the data loss, you can try to search in the repo discussions or issues as @tommoor has explained how to do it manually.

**Comment by Limezy** [comment]
Found it for you : https://github.com/outline/outline/issues/3388

**Comment by tommoor** [comment]
☝️ The "edit" mode is basically in maintenance right now – I would recommend to stick with collaborative editing and it will be required for new features going forward eg comments.

**Comment by jonatcb** [comment]
Thanks @Limezy and @tommoor for quick reply. I guess we'll keep it on as you suggest and I'll just tell folks to be very careful until the 'edit' mode is live!

**Comment by tommoor** [comment]
We could potentially allow disabling/enabling but It would also require clearing the local document cache in everyone's browser so it's quite complicated – we just don't have the resources right now so disabling the toggle was a quick way around it.

**Comment by psifertex** [comment]
Wow, at least put a warning box there, this is awful! Just enabled this option on an install and now the wiki is completely broken for some unknown reason (everyone gets the "not connected" icon in the corner). Not being able to simply turn this back off (immediately after turning it on) means that we now have to either live with a completely uneditable wiki or take a bunch of time to troubleshoot it _right now_. :-(

**Comment by psifertex** [comment]
Put my money where my mouth is. 😛 
https://github.com/outline/outline/pull/3618

**Comment by tommoor** [comment]
> Just enabled this option on an install and now the wiki is completely broken for some unknown reason

You should be aware that this is indicative of wider issues with your installation with websockets – and collaborative editing is just _exposing_ this because it makes more use of the realtime aspects. Even with collaborative editing disabled you should investigate why websockets are not able to connect, they probably need forwarding through the proxy correctly.

**Comment by psifertex** [comment]
Yup, I figured that out relatively quickly! (interestingly, no useful errors in the client side chrome dev console) 

However the wiki went from fully functional as far as I could tell to totally broken pretty quickly. Not sure what other features use the websockets but there was zero indication they weren't working but should have been before this point. It would have been one thing had that happened when I was doing an upgrade but was certainly a surprise when enabling a feature slider that was irrevocable.
