### ISSUE TITLE
Document updates not being pushed to Slack

### ISSUE THREAD

**Issue by accesstechnology-mike** [outline/outline#3778]
New documents work fine, but documents that are updated and auto-saved do not send notifications

**Comment by tommoor** [comment]
Hi Mike, please follow the template for reporting bugs as there is not enough information here.

**Comment by accesstechnology-mike** [comment]
**To Reproduce**
Steps to reproduce the behavior:
1. Open existing document
2. Click anywhere to being editing
3. Document autosaves

**Expected behavior**
Slack Integration settings state: "Connect Outline collections to Slack channels and messages will be automatically posted to Slack when documents are published **or updated.**"

Auto-saved documents do not push notifications to Slack as expected. 
(new documents do push notifications, so the integration is working)

**Outline**
- Install:  self-hosted
- Version: 0.61.1

**Comment by tommoor** [comment]
Your installation is quite out of date, the issue is likely resolved in the latest build and actually includes controls for which events are sent. You should update the install and see if it persists.

<img width="615" alt="image" src="https://user-images.githubusercontent.com/380914/179483872-c2b2b8c2-98e3-4735-aeb8-f3a7e5bcc92c.png">

**Comment by accesstechnology-mike** [comment]
Ok, thanks, that's working as expected now.
