### ISSUE TITLE
`Enter` in table cell should add a row after the current one

### ISSUE THREAD

**Issue by tommoor** [outline/outline#4129]
Currently it adds a row always at the end of the table

**Comment by PabloYG** [comment]
Hey, I have modified the code to get this behavior. The README says I should comment before submitting a PR, so that's what I'm doing!

The change merely consists of calling `getRowIndex()` when Enter key is detected and using this in the same way we use the `addRowAfter` command. I've also modified `getRowIndex()` for it to work even when there's no Cell selected.

Hope it helps.

**Comment by tommoor** [comment]
Sounds good, bug fixes are always welcome :)
