### ISSUE TITLE
Document changes attributed to wrong user

### ISSUE THREAD

**Issue by Danita** [outline/outline#4267]
Document changes on the History tab are attributed to a user that's not the author of the change.

**To Reproduce**
1. Open a document and do some changes
2. Have a collaborator be on the document with you clicking randomly but not writing anything
3. Abandon the document.
4. See that the history is incorrect and the email notifications quote the wrong person.

**Expected behavior**
That the changes that are highlighted on the History are attributed to the person making the change

**Screenshots**
![imagen](https://user-images.githubusercontent.com/754783/195200853-cbfd2988-d97e-4c20-9592-1b8b51281cac.png)

**Outline (please complete the following information):**
- Install: getoutline.com
- Version: ?

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome 105 and Firefox 105

**Comment by tommoor** [comment]
Hi, currently the last editor in a 5 minute window is attributed to the revision – scrolling and clicking does not count as editing, but removing and retyping a character would.

**Comment by Limezy** [comment]
Could we have multiple authors attributed to one snapshot ? Just like two persons can be co-authoring a commit ? That would make sense for situations where the multiplayer is actually used in parallel by several persons. 

Or at least, because the first option seem like something not that quick to develop, attributing the authoring to the one that has the most characters change in that 5 minutes window ? (This seems easy, but I'm not a dev)

**Comment by tommoor** [comment]
The fix will be deployed at a low-traffic time within the next 12 hours.
