### ISSUE TITLE
Click on pinned document doesn't open it

### ISSUE THREAD

**Issue by Danita** [outline/outline#4268]
Clicking on a pinned document doesn't open it.

**To Reproduce**
1. Pin a document
2. Go to a different collection and back
3. Click on the pinned document, no effect
4. Ctrl + click or middle click on the pinned document, it opens on a new tab.

**Expected behavior**
Clicking on a pinned document opens it.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/754783/195204721-c039d69c-8d19-419b-9b60-eabfb6c72488.png)

**Outline (please complete the following information):**
- Install: getoutline.com
- Version: ?

**Desktop (please complete the following information):**
 - OS: Windowsa
 - Chrome 105

**Comment by tommoor** [comment]
I'm not able to reproduce this one I'm afraid – is it that the document is beginning to drag?

**Comment by Danita** [comment]
Oh yes, it tilts as if I were to drag it.

**Comment by cshaa** [comment]
I'm running into the same issue in Outline v0.87.1 with Firefox 146 on Linux.

I can provide more info, or help debug it, if needed.

**Comment by misha-sunborn** [comment]
Ran into this on a self-hosted 1.9.2 and traced it to the bottom — the root cause is the drag-activation constraint on the pinned cards.

`app/components/PinnedDocuments.tsx` configures dnd-kit's `PointerSensor` with `activationConstraint: { delay: 100, tolerance: 5 }`. That constraint is *time*-based: holding the mouse button for ≥100 ms — which an ordinary deliberate click frequently does — activates the drag sensor even with zero pointer movement. On activation, dnd-kit installs a capture-phase `click` listener on `document` that calls `stopPropagation()` (and removes it only 50 ms *after* pointerup, precisely so it catches the click synthesized by that press), so the click never reaches the react-router `<Link>` — the card does nothing. A fast click (<100 ms hold) cancels the timer and navigates normally, which is why the bug feels intermittent and why quickly repeated clicks "eventually work".

This matches the reports here:

- It only reproduces with **two or more pins**: `isDraggable={items.length > 1}`, so a one-pin Home never shows it — likely why it couldn't be reproduced on demand.
- The card "tilts as if I were to drag it" — that's the sensor activating mid-click.
- Ctrl-click / middle-click always work (those paths bypass the swallowed left-click).

Fix that worked for us: a distance-based constraint instead, `activationConstraint: { distance: 10 }`. A stationary click then never arms the sensor and always navigates, while a >10 px drag still reorders — the standard dnd-kit pattern for elements that are both links and drag handles. Verified on our instance (patched the built chunk): clicks are 100% reliable, drag-reorder unaffected.

The `{ delay: 100, tolerance: 5 }` constraint is still present on `main` as of today.

**Comment by tommoor** [comment]
This should have been addressed last week as part of https://github.com/outline/outline/pull/13498

You can test in nightly or on cloud
