### ISSUE TITLE
Large documents loading for a very long time

### ISSUE THREAD

**Issue by Alemiz112** [outline/outline#5282]
When there is a document with several thousand lines and a bunch of images it takes a lot of time to load. I noticed a bandwidth also increases a lot, which causes it not to even load on slow connections.

**To Reproduce**
1. Create a document with a lot of content
2. Try to open it in a new window or on phone.

**Expected behavior**
The large document loads as fast as small documents. Maybe sending only a part of document, which is visible to the client, would work.

**Version:**  affects all versions; selfhosted

**Comment by tommoor** [comment]
Due to the data model all of the document must be downloaded before being displayed, there is no way around this at this time – I recommend using the sidebar structure to split very large documents into a smaller ones where possible, they will bigger docs will always take longer to transfer.

Closing this out as unactionable for now, if you have a particularly egregious example of bad performance it would be great to see it.
