### ISSUE TITLE
Allow replying to comment notification emails

### ISSUE THREAD

**Issue by tommoor** [outline/outline#5865]
It's quite common that people will reply to comment notification emails, we should allow parsing of those to respond in the thread itself.

Marking as cloud as this needs quite deep integration on the email host in a way that's unlikely to be possible for self-hosters.

**Comment by almereyda** [comment]
Discourse and GitLab do ingestion in convenient, working ways. I suggest to have a look at them. It would be in the interest of our NPO communities to use an equally sufficient online writing system.

Discourse allows individual email addresses per category and per group.

GitLab has service desk email aliases since v17 now.

They, too, do the email processing in the application layer with regular SMTP and IMAP APIs.

I'm not sure if I've seen examples in the Node ecosystem r/n.

Parsing incoming email excitingly also invites for creating new documents from messages and/or certain attachment types.

**Comment by almereyda** [comment]
It's a significant feature request which introduces logic for non-web
Internet protocols (POP3S/IMAPS) with a fair amount of event and state
handling.

Maybe we can find someone to sponsor this, who needs this in their
workflows?
