### ISSUE TITLE
Collapsible region of the `Header` tags should stop at `Page break`.

### ISSUE THREAD

**Issue by zeekhuge** [outline/outline#5895]
Consider the following image :
 
![image](https://github.com/outline/outline/assets/8711218/2e6dc045-bacb-4e02-a722-7956b55d1c0b)
Here,
1. is H2 tag
2. is Page break line
3. is text after the page-break

Now, this is what it looks like after collapsing the `H2` tag at `1`
![image](https://github.com/outline/outline/assets/8711218/7dda8bcc-0c25-465b-807b-8eebc48b94f8)

**To Reproduce**
1. Copy the text from the 1st image
2. Toggle the H2 tags collapse.

**Expected behavior**
The text after the page break should be considered a different page all together and should not be included in previous page's Header tag's region.

**Outline (please complete the following information):**
- Install: v0.71.0

**Comment by tommoor** [comment]
I'm not sure, I can see the argument either way but as page breaks are a relatively underused feature it wouldn't be a big deal to change this behavior.

**Comment by zeekhuge** [comment]
Honestly, the `Header` tag collapsing is a little confusing, and the page-break can serve as an antidote to it.

**Comment by tommoor** [comment]
What is confusing about it?

**Comment by tommoor** [comment]
After considering this for a few days I don't think this behavior should be changed for a couple of reasons.

- Page breaks are for _printing_ only, they don't/shouldn't have an affect on other parts of the layout.
- If you stop collapsing at a page break how do you collapse the content immediately below it? It's not possible.
- Would it stop all collapsing or just the current _level_ of collapsing? Either way the behavior is hard to predict.

Overall, It's best to keep this to headings. I'm rebuilding the heading folding so that the state isn't shared between collaborative editors which will also help.
