### ISSUE TITLE
Cloudflare Access Tunnels give 401 error

### ISSUE THREAD

**Issue by brandoncarl** [outline/outline#6050]
When using Cloudflare Access Tunnels Outline cannot Login.

In the browser it yields a "POST https://outline.example.com/api/auth.info 401"
(note that this is not the actual domain - just being generic for privacy purposes)

The Login splash screen does work.
<img width="264" alt="image" src="https://github.com/outline/outline/assets/5427971/050e58c4-4157-4116-922a-0683679b3c32">

This may be related to the same root cause as https://github.com/outline/outline/issues/5718

Thanks in advance for the help

**To Reproduce**
1. Set up Outline with a URL parameter set for external access
2. Set up a Cloudflare tunnel via their Zero Trust. Create both the Application and Tunnel
3. Go to the URL to try to log in

**Expected behavior**
POST auth.info works

**Screenshots**
See above

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.72.2

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome

**Comment by toinelin** [comment]
Hi, any news regarding this issue ? Thanks!

**Comment by brandoncarl** [comment]
I am excited about outline as a project, but went ahead and resorted to using Notion instead.

**Comment by toinelin** [comment]
Hi @brandoncarl I finally found the fix for me, maybe it could helps in the future if you want to give Outline another try.

I'm hosting the app using [Cloudron](https://www.cloudron.io/) and Outline is using it for OpenID from it to authenticate users. Cloudron admin is hosted at https://my.cloudron.server and this hostname is behind a Cloudflare Access Applications policy to secure access, asking for user verification and device posture.

My Outline wiki is hosted at https://outline.cloudron.server and use https://my.cloudron.server as OIDC provider.

Because of the policy rules applied to https://my.cloudron.server, Outline was unable to reach the OIDC endpoint. To resolve that I created a new Access Group with IP ranges related to Cloudflare IPs and my private network IPs.

You can find Cloudflare IP ranges here:
- IPv4: https://www.cloudflare.com/ips-v6
- IPv6: https://www.cloudflare.com/ips-v6

I use this new Access Group as a bypass policy in my Cloudflare Access for https://my.cloudron.server and it works well now.

**Comment by brandoncarl** [comment]
Thank you - I’ll keep in mind if I try again!
