### ISSUE TITLE
New child document is difficult to find

### ISSUE THREAD

**Issue by tommoor** [outline/outline#625]
Creating a new child document is difficult to find. No one at Ada Support knew how to do it.

- [x] Update this to say "New child document" ?

![image](https://user-images.githubusercontent.com/380914/37869505-dc842342-2f75-11e8-8dd8-d29da36f573b.png)

- [ ] Introduce the "..." menu for documents in the sidebar the same way as we have for collections to insert children?

![image](https://user-images.githubusercontent.com/380914/37869536-39a89b70-2f76-11e8-9a3a-75f6faa12d52.png)

**Comment by jasonquiz** [comment]
I like the "..." suggestion recommended above, but I think it would be good to change the functionality 
 of the "New Document" icon so that it always creates a new sub document.

If you are on the "Channels" page, clicking that icon makes a Document within the Channel.

It would then make sense then that clicking on that icon when in a Document would create a Child / Sub Document. Right now it creates a document at the same level and breaks the paradigm. 

---

Another option is to let the user do both and put a second (visually different) icon to the right of the "New Document" icon (see image).

![new-child](https://user-images.githubusercontent.com/961853/39544515-28f0db20-4e03-11e8-8a72-3103953256f5.jpg)
