### ISSUE TITLE
Import fails / Failed • EISDIR: illegal operation on a directory, read. Check server logs for more details

### ISSUE THREAD

**Issue by KingBBQ** [outline/outline#6273]
trying to import a markdown zip file incl. some images.

**To Reproduce**
1. Go to 'Settings' - Import Markdown
2. Upload the ZIP File
3. wait..
```

outline_1   | {"dirPath":"/tmp/tmp-47-rchXQ1Ez8vS3","label":"task","level":"info","message":"ImportTask parsing data for 842e162b-d9fa-4596-a205-f96b0369296e"}
outline_1   | {"attempt":0,"event":{"actorId":"3c1c2dec-b62e-412d-af44-503aff36e32f","createdAt":"2023-12-10T11:02:22.393Z","id":"ac69671c-3827-479f-ab82-7c506b6271dc","modelId":"842e162b-d9fa-4596-a205-f96b0369296e","name":"fileOperations.update","teamId":"46ef1129-0e1b-4457-9f43-affdc3b3f2db"},"label":"worker","level":"info","message":"Processing fileOperations.update"}
outline_1   | {"event":{"actorId":"3c1c2dec-b62e-412d-af44-503aff36e32f","createdAt":"2023-12-10T11:02:22.393Z","id":"ac69671c-3827-479f-ab82-7c506b6271dc","modelId":"842e162b-d9fa-4596-a205-f96b0369296e","name":"fileOperations.update","teamId":"46ef1129-0e1b-4457-9f43-affdc3b3f2db"},"label":"worker","level":"info","message":"WebhookProcessor running fileOperations.update"}
outline_1   | {"error":"EISDIR: illegal operation on a directory, read","level":"error","message":"Error processing task in ImportMarkdownZipTask","stack":"Error: EISDIR: illegal operation on a directory, read"}
```
the upload works, the zip file is in the data directory.

**Outline (please complete the following information):**
- Install: selfhostet / ubuntu. docker version behind a traefik proxy
- Version: latest

**Comment by tommoor** [comment]
So it's trying to read a directory as if it's a file, which would definitely seem like a logic bug. Are you able to provide the zip file for debugging? Where does the zip file come from, another export from Outline or manually constructed?

**Comment by KingBBQ** [comment]
Checked the zip file again: it had a ".git" subdir in it, didn't see it first, as it was hidden. Removing this fixed the problem :) sorry for the "wrong" but report!

**Comment by tommoor** [comment]
I'll keep this open and add logic to ignore hidden directories

**Comment by Mekacher-Anis** [comment]
sorry for re-opening but I hit this exact same issue while trying to import an empty directory.
I exported a complete notebook from Joplin and tried importing it, it had one empty folder in it and it was trying to read it.

**Comment by tommoor** [comment]
If attempting to import random zip files that are not in the expected format then read errors such as this seem expected 😄

**Comment by Meldanor** [comment]
I encountered this problem today while importing a Notion HTML export. It took a while to pin point the issue because the filename of the failing directory is missing.

Here is the situation:
- 314 files, 62 subfolders in ttoal (the export itself is 35 MB big)
- Two of these folders contain only one file
  -  This file is "ignored"? In the console is a "Unhandled file in zip" error, but without a reason why it is unhandled?
- Because these files are "ignored" the directory is read and the error occured.

Even with only the problematic folders the error is reproducable. I've attached them (Problematic folders are "Schrank,den man ansturren muss" and "Stufen der Lord").

I think the general issue is the naming format of the files?

[minimal_copy.zip](https://github.com/user-attachments/files/18992831/minimal_copy.zip)

**Comment by muuvmuuv** [comment]
We migrated our DokuWiki (around 94 MB of txt and 1 GB of data) and got it fixed by running these steps:

- Fix image paths and remove starting `/`: `<img="/`
- Remove embeds: `<embed[\n\d\D]*?/>`
- Delete empty dirs: `find . -type d -empty -delete`
- Fix permissions: `chmod -R 755 .`
- Remove other files: `rm -rf **/*.{mp4,odt,pdf,doc,docx,zip,7z}` (we decided to move them to some storage solution ^^)

Especially empty directories caused an error.
