### ISSUE TITLE
tldraw integration does not show content

### ISSUE THREAD

**Issue by glungtung** [outline/outline#6706]
On my v0.75.2 self-hosted outline, when I insert a tldraw link in my outline document, or when i use /tldraw integration with my tldraw link, i have a white frame with a "Visit this page on tldraw.com" link. The link is working properly, but i don't see tldraw content in the integrated frame 
I've tried this with different tldraw document type : shared link, read-only link, snapshot link

**To Reproduce**
1. type /tldraw, enter
2. paste my tldraw document link

**Expected behavior**
a frame with my tldraw document content

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
<img width="817" alt="Capture d’écran 2024-03-24 à 11 17 09" src="https://github.com/outline/outline/assets/457189/e10c185b-cee0-4908-961b-a259a874e0d9">

**Outline (please complete the following information):**
- Install:  self hosted
- Version: v0.75.2

**Desktop (please complete the following information):**
 - OS: macos
 - Browser : firefox, safari and chrome = same behavior

**Comment by tommoor** [comment]
It seems as though tldraw may have blocked embeds entirely, checking with their team…

**Comment by glungtung** [comment]
I found a working embed there : https://tldraw.dev/

**Comment by Squiddim** [comment]
Hi this issue Stems from tldraw Side blocking iFrame integration of their Hosted version. I suggest natively integrating their SDK into the Codebase
also see #4174

**Comment by tommoor** [comment]
Yes, I'm talking to the founder of TLDraw – this is likely a temporary limitation on their side while they figure out how to make embeds enabled again without inviting abuse.

**Comment by DeathDreamZz** [comment]
@tommoor Thx for looking into this matter :) 
but why not integrate their SDK imho thats what tldraw is designed to do instead of relying on their hosted service?

**Comment by Squiddim** [comment]
@tommoor Thx for looking into this matter :)
but why not integrate their SDK imho thats what tldraw is designed to do instead of relying on their hosted service?

**Comment by elysweyr** [comment]
> Yes, I'm talking to the founder of TLDraw – this is likely a temporary limitation on their side while they figure out how to make embeds enabled again without inviting abuse.

Thanks! Integrating tldraw would be indeed very neat but I wouldn’t expect that much from negotiations. That’s because they’re changed course very drastically (went de-facto closed source). Therefore I would suggest to fork the last version of tldraw published under Apache license and ditch copyright infringing material. 

It’s very hard to build open source software based on closed source components with very harsh usage limitations.

What do you think? @tommoor 

(Disclaimer: this activity is purely dedicated to my free time projects and not related in any way to my employment.)

See: 
https://github.com/tldraw/tldraw/blob/main/LICENSE.md
https://github.com/tldraw/tldraw/blob/6bd7f4fcc97bbecda6785968c64c2814ea25452f/LICENSE

**Comment by tommoor** [comment]
The current integration is just a quick way for folks to preview TLDraw links within Outline. The maintainer has suggested they plan on re-enabling this iframing ([source](https://twitter.com/steveruizok/status/1776966777848635415)) once abuse has been dealt with (understandable).

While there might be some thought behind integrating a fully integrated drawing interface into Outline that would be a _much_ larger project, especially as Outline has it's own multiplayer framework, storage requirements, etc.

FWIW I'm not dogmatic about OSS here – we integrate with lots of commercial products because the reality is these often have a better UX and larger user numbers.

**Comment by Squiddim** [comment]
btw the iframe just started working again

**Comment by tommoor** [comment]
Nice, yes – looks like it was fixed here https://github.com/tldraw/tldraw/commit/c0b192033eded4ca9e0d574b8c05a9567cc14083

**Comment by glungtung** [comment]
Hello,
On my v0.82.0 self-hosted outline, when I insert a tldraw link in my outline document, or when i use /tldraw integration with my tldraw link, it's not working. 
I've tried with "invite" and "publish" links, i get no iframe
thanks

**Comment by tommoor** [comment]
Are you sure embeds are enabled in the document and in the security settings?

**Comment by glungtung** [comment]
yes I'm sure
if I put an old fashionned link, it works. I've found an old link in my documents and it works if i paste it, like this : 
https://www.tldraw.com/r/3tQnCJAuussFShYTf0Win?v=0%2C0%2C1475%2C756&p=page
I can see a /r in the url

but on today's tldraw website, i can only get links with /f or /p

**Comment by tommoor** [comment]
Gotcha, they keep changing the url format – but you can always embed with the plain embed command for this one it will work the same actually.

**Comment by glungtung** [comment]
what do you mean "the plain embed command" ? I've searched everywhere but i cannot find the old-way url for a new tldraw graph

**Comment by almereyda** [comment]
I think Tom was talking about a generic iframe embed for any URL.
