### ISSUE TITLE
Excalidraw integration

### ISSUE THREAD

**Issue by tommoor** [outline/outline#6794]
### Discussed in https://github.com/outline/outline/discussions/4940

<div type='discussions-op-text'>

<sup>Originally posted by **lumoe** February 26, 2023</sup>
[Excalidraw](https://github.com/excalidraw/excalidraw)  is an awesome, yet simple piece of software that enables hand collaborative whiteboard drawing. An alternative to that is [tldraw]( https://github.com/tldraw/tldraw), where there already exists a FR: https://github.com/outline/outline/discussions/4174. There is also an implementation for the [Obsidian](https://github.com/zsviczian/obsidian-excalidraw-plugin) note-taking app for Excalidraw as a reference. 

As far as I am concerned, there is no possibility to have a public link share from the [website](https://excalidraw.com/)—so the implementation should work within outline. </div>

**Comment by tommoor** [comment]
Blocked by https://github.com/excalidraw/excalidraw/issues/2706

**Comment by dant2021** [comment]
Watch out tldraw is not open source and have rent seeking behavior. We are currently switching away from them.

**Comment by nightpool** [comment]
@tommoor since excalidraw is available as an NPM package, would there be an approach to this where the scene data is saved and updated within outline, instead of using the share link approach? Then, since Outline is in control of the data at all time there would be no issues with the lack of updates.

**Comment by gabriel-ss** [comment]
Hey @tommoor,

First off, thank you for your work in Outline, it’s an amazing platform! We’re in the process of migrating our internal docs to it at work. My boss has asked me to create a fork and add support for embedding Excalidraw diagrams. He also allowed me to contribute any improvements back to the project.

If you're open to it, I would like to take a shot at implementing this feature. As many have mentioned in other discussions, Excalidraw is available as a React component and can export SVG files with embedded metadata for further editing. My current plan is to implement something similar to #10707, but with the Excalidraw editor opening in a modal rather than an external page. I’m aiming to follow a similar approach to how Docmost handles it:

<img width="3705" height="1874" alt="Image" src="https://github.com/user-attachments/assets/f0a4e8cc-1454-4dfe-a1f0-c9f67a9968da" />

Please, let me know if you would be interested in a PR!

**Comment by tommoor** [comment]
Hey @gabriel-ss – honestly we already have TLDraw, Mermaid, Diagrams.net – there is a very long tail of drawing tools and I don't think we'll be adding anymore into the platform for now. You can always use the `/embed` command to iframe any page that allows it.

**Comment by Rodaviva29** [comment]
Very excited for an update from a member. But That’s actually a bit sad to hear. I would prefer Excalidraw over the alternatives. Well, but is what it is. 😕

**Comment by Darkdragon84** [comment]
I agree. Excalidraw would offer true multiplayer collaboration which would fit very well in the overall outline collaboration paradigm. While Mermaid already offers this, it is just way too restricted and basic for a lot of applications. Excalidraw is just much more modern and robust. 

Re `/embed`, just embedding an excalidraw live session link to the room doesn't work, as the local canvas won't sync with the actual excalidraw room. It's pretty much the same as just putting the link to the room. In fact the iframe is misleading, because it just creates a local canvas that can be edited without any connection to the actual target room.

**Comment by Heidi-Negrete** [comment]
Check out [ExcaliDash](https://github.com/ZimengXiong/ExcaliDash#). I self-host outline and I just needed to embed a link to one of the excalidash drawings. We're getting real-time collab and persistence.
