### ISSUE TITLE
Workspace templates

### ISSUE THREAD

**Issue by tommoor** [outline/outline#6978]
Currently templates need to belong to a collection, this is somewhat restrictive as many templates would work well at a workspace level - for example "Meeting notes". Recently we've seen folks creating collections just to create templates and this is a pattern that has a lot of downsides, instead we should just support templates without a `collectionId` being visible to all workspace members.

**Comment by hmacr** [comment]
I'd like to work on this.

This is quite straightforward.
Server needs to validate the `collectionId` as optional only when it is a template doc. Also needs to return the required policies for a "collection-less" template.. App needs the corresponding impl.

**Comment by tommoor** [comment]
Right on 🫡

**Comment by hmacr** [comment]
Currently, a team member can templatize an existing doc. They will be able to edit it when they first make the copy; post that, it's not possible for them to edit since we hide the `Templates` page for non-admins. This provides a sub-optimal UX imo.

Perhaps, we can show the `Templates` page to all the members with restricted edit permission per template - either they should be an admin (or) be the creator of the template.

@tommoor Do you think we should implement this?

**Comment by tommoor** [comment]
Yes, that sounds fine – may have gone too far by hiding templates from users completely in this case.
