### ISSUE TITLE
Diagrams.net integration for self hosted instance if diagrams.net

### ISSUE THREAD

**Issue by rishabhrkaushik** [outline/outline#7265]
I have a nextcloud instance running with diagrams.net app. I've created a diagram and made a publicly available sharing link for the file. I want to embed this file on outline with diagrams.net integration. When I paste the link, it says that embed for such link is not supported by integration. 

**To Reproduce**
1. Create a diagrams.net diagram and save file in cloud with public URL
2. Copy URL to the integration

**Expected behavior**
Diagrams.net integration should work with file link irrespective of the source atleast if the link is public. 

**Outline (please complete the following information):**
- Install: Self hosted
- Version: 

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser: Opera

Similar to
[Issue 2831](https://github.com/outline/outline/issues/2831)

**Comment by dantesia** [comment]
The problem is that previously the link that was created on the website diagrams.net was in https://**viewer**.diagrams.net/?tags= format, and now after some updates in diagram services https://**app**.diagrams.net/?tags=


Now there are 2 ways:
1. manually change "app" to "viewer" in each link before insert link
2. Rework and check the integration in outline. Changing "viewer" to "app" in the outline code Does not help. - after changes and rebuild after insert link  i got "working integrations", but  error and some code (don't remember) in window of intergration (but no preview diagrams)
sorry for my english

**Comment by tommoor** [comment]
Did you configure the integration in Settings -> Integrations -> Self Hosted?

**Comment by routerino** [comment]
Pointing to the self-hosted drawio works for me.

remember to set the setting in the selfhosted section.

For the drawio container, you need to set DRAWIO_LIGHTBOX_URL with a trailing . (it's not a typo)
```yaml
environment:
        - DRAWIO_LIGHTBOX_URL=https://drawio.yourdomain.com.au/.
```

**Comment by Lucas668** [comment]
could you show the usage result and share the integration step by step?  I very want to have the drawio pluin like that which in the docmost ( https://github.com/Docmost/docmost )

**Comment by Lucas668** [comment]
> Pointing to the self-hosted drawio works for me.
> 
> remember to set the setting in the "Self Hosted" settings inside outline.
> 
> For the drawio container, you need to set DRAWIO_LIGHTBOX_URL with a trailing . (it's not a typo)
> 
> environment:
>         - DRAWIO_LIGHTBOX_URL=https://drawio.yourdomain.com.au/.
> Then your drawio instance will generate links that point directly back to your selfhosted instance.

could you show the usage result and share the integration step by step? I very want to have the drawio pluin like that which in the docmost ( https://github.com/Docmost/docmost )
