### ISSUE TITLE
Linking to an anchor in the same document

### ISSUE THREAD

**Issue by tommoor** [outline/outline#739]
Doesn't work as expected. I think links that begin with '#' need special treatment.

**Comment by amassis** [comment]
Here is what I could notice:
1) h1's generate an anchor and a link automatically - not sure why that is - they link to themselves.
ou can see that by hovering over the end of any h1 and you will notice a "#" sign - and a link in the status bar says "Go to #header-title-text" (screenshot below). If you click that link, it works - you can see the page "jump" to that position, even though it is not as useful, the link actually works.
<img width="1285" alt="screen shot 2018-08-04 at 22 35 42" src="https://user-images.githubusercontent.com/10330917/43681878-a526ff66-9837-11e8-8abb-fdcbf6956bf9.png">

2) I tried creating a table of contents on the top of the page but I didn't know how to refer to those links. I tried both adding links in these two formats, neither one works: 

a) This causes the browser to open a new tab with the same page. It doesn't browse to the anchor in the same page as expected.
`#header-title-text`
b) This doesn't do anything
`https://www.getoutline.com/doc/my-page-name-and-id#header-title-text`


3) Curiously, hovering over the link I created with the full url - it shows me a different message in the status bar as "Open #header-title-text" (notice "Open" rather than "Go to" as mentioned in #1 - screenshot below)

<img width="1286" alt="screen shot 2018-08-04 at 22 36 02" src="https://user-images.githubusercontent.com/10330917/43681881-b2f1ca68-9837-11e8-80f0-047b01c904fc.png">

I hope this helps somehow :)
Thanks
Alex

**Comment by tommoor** [comment]
Will definitely take a look into it! One thing you might not have noticed - the table of contents is automatically generated and can be seen by hovering your mouse on the right hand side of the document.

It might make sense to introduce an option to show it at the top of the document instead.

**Comment by amassis** [comment]
Hmmmm I had not seen that. I noticed a few small “lines” on the right margin of the page, but couldn’t figure out it was a ToC. They are very discrete :)
Thanks!


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tommoor** [comment]
So a couple of key takeaways from this…

- [ ] Clicking on the "#" next to headings should copy a link to the clipboard
- [ ] Visiting a link with a "#" should correctly jump to the heading (this seems to be broken)
- [ ] Ensure that manually creating links beginning with "#" works as expected
- [ ] Make the table of contents more obvious (optionally at the top of document?)

**Comment by jasonquiz** [comment]
Regarding making the ToC more obvious (which I agree with, I usually forget
they are there), one idea I have is to let the user, while in edit mode,
insert a ToC into the document using the (+) button. Just make it another
insert option.

This way if you want to add it you can. You also have the ability to add it
anywhere in the document that you think makes sense.

**Comment by amassis** [comment]
@tommoor perfect summary
@jasonquiz it is very common in wikis to be able to include a ToC on the top of a page, so, I would say it is definitely a good one :+1:

**Comment by amassis** [comment]
Just a couple more details:
1) If you click any ToC item, it goes to the proper place, but the Header gets hidden behind the navbar (where the breadcrumbs are)
2) If you create a "Child Page" it goes below the "parent page" in the navigation to the left - but there is no reference inside the "parent page" as to the existence of children (i.e. Child Pages don't appear in the ToC and I couldn't find any indication there is a child page - other than the nav to the left. This is not very intuitive when reading.

**Comment by tommoor** [comment]
Hey @amassis fix incoming for the hidden behind navbar issue.

For the child documents, the sidebar is the place to find those for now. It's likely we'll introduce a nav at the bottom of the document to skip to children / next sibling but I'd consider that a separate issue. I want to make sure the scope of this one doesn't balloon :)
