### ISSUE TITLE
Subscribe to a document

### ISSUE THREAD

**Issue by tommoor** [outline/outline#743]
It would be nice to have the ability to optionally "watch" or subscribe to a document and get notifications when it is updated. Give this issue a reaction if you agree 👍 

Related #2167

**Comment by almereyda** [comment]
It seems this is already partly present, since people get email notifications about changes in documents already, which are improved with #1146. Also different levels of subscription become imaginable, as with the GitHub Watch function, or the Discourse Watching/Tracking/... levels.

To begin an informal design braintorm as suggested by the tag added above, such subscrition levels could break down into:

Watch:

- minor edits  
  changes within content blocks
- major edits  
  added or removed content blocks
- references
  a link to the page has been added/removed on another page

And there is other useful "administrative" information we might wish to audit, e.g. if:

- permissions are changed
- users added or removed
- public links are created or removed
- the document got deleted

Which other scenarios come to your mind, when sketching this feature in your imagination?

**Comment by tommoor** [comment]
closed in https://github.com/outline/outline/pull/3834

**Comment by tommoor** [comment]
Released in `v0.66.0`
