### ISSUE TITLE
Switch to `dockerhub` as source for "versions behind" notification

### ISSUE THREAD

**Issue by tommoor** [outline/outline#7700]
Currently we use the GitHub releases API to detect if the installed community edition is behind – this works well for community, but not for the enterprise image as there is no corresponding GitHub release. Instead we should switch to using the dockerhub API as the source for this information:

https://hub.docker.com/v2/repositories/outlinewiki/outline/tags?name=&ordering=last_updated&page=2&page_size=10

**Comment by AlexandrZagorskiy** [comment]
Hi @tommoor ,

I’ve been exploring the issue you raised regarding version checking for the enterprise edition, and I’d like to share my approach. Here's what you can expect:

### Approach:
1. **New `DOCKERHUB_REPO_URL` environment variable**:
   - I’ll add this variable to the `.env` file to allow dynamic configuration for both the community and enterprise editions. The URL will be compiled based on the edition in use.

2. **Modification of the UI version check**:
   - I’ll update the current UI logic (found in `Version.tsx`) to fetch version information from DockerHub using `DOCKERHUB_REPO_URL`, instead of relying solely on the GitHub Releases API. This will make the UI capable of showing version status for the enterprise image hosted on DockerHub.

This change can serve as a foundational step towards addressing the request in [Discussion #7168](https://github.com/outline/outline/discussions/7168), which involves making the version accessible through the Outline Rest API. After the initial UI implementation, we can build on this to allow querying version data via the API.

### Expected Outcome:
Once this PR is merged, the UI will correctly display whether the installed enterprise version is up-to-date based on DockerHub data, just like it currently does for the community edition with GitHub.

Please let me know if this aligns with your expectations or if there are additional points you'd like me to consider!

**Comment by tommoor** [comment]
Hi, I wasn't really expecting anyone else to take this on, but if you want to that's fine.

There is no need to make the URL an environment variable, just hardcode it the same way that the GitHub URL is today

**Comment by AlexandrZagorskiy** [comment]
During my work on switching the version check from GitHub to DockerHub, I encountered an issue related to CORS when trying to fetch data from DockerHub directly on the client-side. Interestingly, GitHub's API does not trigger this problem, but DockerHub’s API does.

> Access to fetch at 'https://hub.docker.com/v2/repositories/outlinewiki/outline/tags?name=&ordering=last_updated&page_size=10' from origin 'https://local.outline.dev:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

To resolve this issue, my proposed solution is to create a server-side proxy. Here’s the plan:

- I’ll create a new API endpoint, `getVersionsInfo`, that will fetch the version data from DockerHub server-side. This bypasses the CORS issue.
 - The endpoint will return the **current version**, the **latest version** from DockerHub, and the **number of versions behind** the current version is.
   
**Example URL**:
   - `POST https://app.getoutline.com/api/versions.getVersionsInfo`

**Expected Response**:
   ```json
   {
     "success": true,
     "data": {
       "currentVersion": "0.80.1",
       "latestVersion": "0.80.3-0",
       "releasesBehind": 2
     }
   }
   ```

This endpoint could later be extended to provide more detailed version data via the Outline API (related to Discussion #7168), but initially, it would only be used to solve the CORS issue.

Does this approach seem suitable to you, or do you have another suggestion for how we could handle this problem?

**Comment by tommoor** [comment]
> To resolve this issue, my proposed solution is to create a server-side proxy. Here’s the plan:

Yes, probably the best idea longrun anyway 👍 – as for example it allows for more effectively caching and would close https://github.com/outline/outline/issues/7169 at the same time.

> The endpoint will return the current version, the latest version from DockerHub, and the number of versions behind the current version is.

Sounds good. I would suggest not using `versions` as it's a bit overloaded with document versions. 

### Suggestion

**Example URL:**

POST https://app.getoutline.com/api/installation.info

**Expected Response:**

{
  "success": true,
  "data": {
    "currentVersion": "0.80.1",
    "latestVersion": "0.80.3-0",
    "releasesBehind": 2
  }
}

**Comment by AlexandrZagorskiy** [comment]
@tommoor btw If PR is merged, should Issue be solved?

**Comment by AlexandrZagorskiy** [comment]
@tommoor btw If PR is merged, should Issue be solved?
