### ISSUE TITLE
Add user preference to disable smart quotes

### ISSUE THREAD

**Issue by tommoor** [outline/outline#7769]
If you're writing a lot of inline code this can get in the way, I think it makes sense to have a preference to opt out of this behavior.

**Comment by infinite-persistence** [comment]
<details>

<summary><h1>Proposal ...</h1></summary>

## UI
- In Preferences Page, add setting row to turn Smart Text on/off.
    - <img src="https://github.com/user-attachments/assets/b0582341-7694-4249-b0ba-cf088c16ddad" width="200">
- Optional: modal to configure individual smart-texts.
    - <img src="https://github.com/user-attachments/assets/5855e93d-29dc-4756-91e1-78ba40acffb0" width="200">

## Code

1. **Add:**
   ```javascript
   export enum UserPreference {
     ...
     /** Whether Smart-Text (InputRules) should be enabled. */
     EnableSmartText = "enableSmartText",
   }
   ```
2. *(if individual configuration is desired)* **Add:**
   ```javascript
   export enum UserPreference {
     ...
     /** Whether Smart-Text should be enabled in general. */
     EnableSmartText = "enableSmartText",
     /** Selective Smart-Text items to enable */
     EnableSmartTextRightArrow = "enableSmartTextRightArrow",
     EnableSmartTextEmdash = "enableSmartTextEmdash",
     EnableSmartTextOneHalf = "enableSmartTextOneHalf",
     EnableSmartTextThreeQuarters = "enableSmartTextThreeQuarters",
     EnableSmartTextCopyright = "enableSmartTextCopyright",
     EnableSmartTextRegistered = "enableSmartTextRegistered",
     EnableSmartTextTrademarked = "enableSmartTextTrademarked",
     EnableSmartTextEllipsis = "enableSmartTextEllipsis",
     EnableSmartTextOpenDoubleQuote = "enableSmartTextOpenDoubleQuote",
     EnableSmartTextCloseDoubleQuote = "enableSmartTextCloseDoubleQuote",
     EnableSmartTextOpenSingleQuote = "enableSmartTextOpenSingleQuote",
     EnableSmartTextCloseSingleQuote = "enableSmartTextCloseSingleQuote",
   }
   ```
   - On the fence whether to "add to enum" or "create new enum"
     | Implementation Option | Pros | Cons |
     | --- | --- | --- |
     | 1. Add to `UserPreference` | No changes needed in `User` model | Quite ugly |
     | 2. Create new enum `SmartTextType` | Cleaner | `User` needs new setter/getter (questionable as it's still a "user preference"). Some work on the DB side too? |
3. Tweak `SmartText.inputRules` to return list of rules based on settings in `User` store.
   - The `PasteHandler` extension accesses the store directly as well (rather than being injected), so I'll assume it's fine for extensions to access the store.
   - The setting is only loaded to the editor on entry, so changing the setting through another tab will not affect existing opened editors until they reloaded. I think this is fine?
   ```javascript
    inputRules() {
      const enableSmartText = 
        stores.auth.user?.preferences?.enableSmartText ?? UserPreferenceDefaults.enableSmartText;
  
      return enableSmartText ? [
        rightArrow,
        emdash,
        oneHalf,
        threeQuarters,
        copyright,
        registered,
        trademarked,
        ellipsis,
        openDoubleQuote,
        closeDoubleQuote,
        openSingleQuote,
        closeSingleQuote,
      ] : [];
    }
    ```
4. Migration
   - Not familiar with this, might need help here.

</details>

**Comment by tommoor** [comment]
- UI– location is fine, lets call it "Smart text replacements"
- A single boolean in (default: true) `UserPreference` is fine, no more granularity needed
- It's not possible to access the store inside the editor, instead the SmartText extension should only be added to the editor if the setting is enabled. For example [here](https://github.com/outline/outline/blob/21723d3ca2611e72e380db03512f8b8732968d25/app/scenes/Document/components/CommentEditor.tsx#L16) we can memoize the extensions array and access the user preference.
- No migration needed
