### ISSUE TITLE
Cannot access the main content at www.getoutline.com when logged in.

### ISSUE THREAD

**Issue by kjano** [outline/outline#779]
Okay, so maybe this is a feature and not a bug but it certainly is unintuitive. As long as I am logged-in in slack and getoutline, I cannot access the official getoutline homepage, e.g., to navigate to https://www.getoutline.com/#features.

**Comment by tommoor** [comment]
It's definitely how it's designed today, it would be easier almost to not forward to the dashboard but I think if you're logged in you're way more likely to want to get to your wiki than look at the home page 😄

**Comment by kjano** [comment]
Well, yes, but if you want to look up a feature or the API documentation, you always have to log out of Outline first. It is a minor issue, but I wanted to bring it to your attention.

**Comment by tommoor** [comment]
Appreciate you filing @kjano, I'm going to close as by design right now but we'll consider this when working on the homepage again in the future. If anyone stumbles on this in the meantime you can access the API documentation from the account menu:

![image](https://user-images.githubusercontent.com/380914/46266019-cb759800-c4e0-11e8-83ca-b48ebd9962bf.png)
