### ISSUE TITLE
Add trash menu item

### ISSUE THREAD

**Issue by tommoor** [outline/outline#808]
Add a "trash" menu item, I think this would make the most sense below the "collections" section – that would show a list of documents recently deleted and allow for them to be restored.

**Comment by teddychan** [comment]
+1

Our team just found that one of the files is deleted and wanna to recover it.

**Comment by tommoor** [comment]
Hey @teddychan – thankfully as you're hosting it yourself you can recover by removing the timestamp in the `deleted_at` column in the database 😄

**Comment by satyadeepk** [comment]
@tommoor What do you think about this approach for showing deleted docs? https://github.com/SheroesDev/outline/commit/b7ddd5e045f87c3849d57b253be3a4e1f6155ca1

<img src="https://user-images.githubusercontent.com/478578/49690539-e441a000-fb58-11e8-87dd-1de599fc7d2a.png" width=450 />

I noticed an issue with my implementation though. Clicking on the collection after going to Trash, the deleted item is visible - because the deleted item is getting added to the Document store. 
That would mean `deletedAt` filter has to be added in all other `DocumentStore` filters as well. Not very clean.

**Comment by satyadeepk** [comment]
`orderedData` is currently being only used in `starred`. The others directly use `this.data.values()`. We will probably need a new computed prop in the `BaseStore` which removes deleted items and use it everywhere. 
Or I can use `orderedData` itself everywhere removing deleted items.

**Comment by tommoor** [comment]
> if we are restoring Doc D, should we restore all the docs above in it's hierarchy as well 

Yea, it seems like that would be necessary…

**Comment by satyadeepk** [comment]
It seems more involved and tricky than I first expected!
What should happen in the case when a whole collection is deleted? Should we restore the collection as well, when one of it's documents is being restored?

**Comment by tommoor** [comment]
I think it would be fine to keep trash to just deleted docs in a first pass if that makes things significantly simpler.

If not, then yea restoring the collection seems like the way to go!

**Comment by tommoor** [comment]
Closing this out in favor of "archiving" documents, which is now on master

https://github.com/outline/outline/pull/921
