### ISSUE TITLE
Document Title bug when bulk importing from .docx

### ISSUE THREAD

**Issue by tommoor** [outline/outline#8090]
### Discussed in https://github.com/outline/outline/discussions/8089

<div type='discussions-op-text'>

<sup>Originally posted by **adriansoewono** December  9, 2024</sup>
Hi, it seems to me the Document Title is buggy when I tried to bulk import from .docx files which has a dot character in the filename.

so to reproduce:

1. all my current document filename structure has a number+dot prefix (so I can set the document order easily).
I have to use .docx files because I need to import images easily.
![Screenshot 1](https://github.com/user-attachments/assets/b26f3304-6208-49da-8a6a-8843ddd881ac)

2. I bulk import it using files drag and drop
![Screenshot 2](https://github.com/user-attachments/assets/59ce8bbb-345c-4319-b16f-db26c04b29bc)

3. then the document title in the Outline shows like this, there's a backslash character before the dot.
![Screenshot 3](https://github.com/user-attachments/assets/85a87f53-f977-4c3d-b2ed-57d5b3c37fb2)

apparently this happens only in .docx import,
I have tried to import .md files, the document title works without any backslash problem for the dot character.

now it seems like a simple bug,
but since all my documents are using number and dot prefix in the filename,
this problem makes me have to rename all my documents in the Outline after importing, which is really a tremendous task.

it will be great if Outline can fix the backslash character bug.</div>

**Comment by adriansoewono** [comment]
I'm actually using the cloud version in the getoutline.com (not self-hosted).

you can check the video here https://www.youtube.com/watch?v=5P5U9RlQpaw

the .docx files I'm using are converted automatically from .md files using Pandoc (universal document converter) from pandoc.org

you can download the .md and .docx files I'm using in
mediafire.com/file/norf59jyaqt8xao
or
https://drive.google.com/drive/folders/1g0A3M9S_dM6_x5b-LtfgO4i5bweKdmCd
(same files)

I have further tested my case,

it seems that Outline generated the document title from the .docx's Page Title -- instead of the .docx filename.

because I have tried to delete the .docx Page Title, so it was an empty document, with the filename of "1. Pengantar.docx" -- and Outline processed it just fine.

but when Outline generated the document title from the .docx Page Title (first heading inside the document), Outline gives an unexpected backslash before the dot character.

hopefully this gives better perspective of the problem.
