### ISSUE TITLE
File Attachments

### ISSUE THREAD

**Issue by tommoor** [outline/outline#859]
This has been requested several times recently. Initial plan would be to integrate with the two largest storage providers, _Google Drive_ and _Dropbox_, rather than building our own file storage service.

On a document you should be able to:

- Attach a file
- Pick an existing file from GDrive/Dropbox or upload
- See a list of files attached to doc
- See which docs have files attached
- Search for files attached to docs

**As always, please add reactions to this issue to vote for it to be implemented 😄**

**Comment by kevalkothari** [comment]
Hi @tommoor  Count me for this feature :) 
It's very useful feature for attaching Sample Template, Small Code File or Other kind of example demos as part of Wiki Doc.

**Comment by JoeyJanson** [comment]
@tommoor Is there any news about this issue? Need contributors or answers for questions before starting with this feature?

**Comment by peiying16** [comment]
It is good to have versionning.

**Comment by aam1r** [comment]
To scope this down for an initial MVP, I think it would be really cool to have file uploads with simple hyperlinks. 

I wouldn't expect it to do any inline embedding. With this approach, you can support any file extension.

Over time, inline embedding can be added for the more popular filetypes such as PDFs, Word Documents, etc.

**Comment by victordariovera** [comment]
I'm using nextcloud as a google drive alternative, but selfhosted for privacy reasons. How I can integrate Nextcloud share links like Google Drive links?

**Comment by tommoor** [comment]
I'm guessing that the url for every nextcloud installation is unpredictable and different? It would make building an embed a much more involved feat than typical embeds where we can regex match

**Comment by victordariovera** [comment]
Maybe the "plugin" or integration can be configurable with nextcloud's domain. Or, maybe can make a get to a know test url in base domain detecting if it is a nextcloud instance. Every nextcloud installation expose a status endpoint for identification of version.

**Comment by etehler** [comment]
Hi! We are using a self hosted Outline mainly because of the lack of good software hosted inside the EU (GDPR).

The only thing that really limits us is the fact that we cannot uploads PDF:s into Outline, and that we cannot embed any videos except from Vimeo/YouTube. A more flexible video-embed and uploading PDF documents into S3 would make self hosted Outline a nice GDPR compliant alternative.

**Comment by acrob0t** [comment]
Regarding the visual appearance of attached files, I've always thought Notion had an appealing [attachment display](https://notion.notion.site/File-uploads-70dfbcd4b2a644f8a019aef94d477488), especially since you can organize files into two columns. I do wish that Notion displayed a logo for major file types instead of just a paperclip though.

Evernote has an attractive attachment display for [Google Drive files](https://evernote.com/google-drive) as well

Is the plan to have a consistent display for files regardless of whether the file is uploaded directly to Outline or a Google Drive/Dropbox "attachment" link.

**Comment by jfmontanaro** [comment]
Just trying to determine the status of this feature - is the official position that the exiting GDrive and Dropbox integrations handle this functionality sufficiently, or are there plans to expand it further? E.g. adding a flow that's similar to the existing image upload, and uses the same backing object store, but displays a link instead of an image.

FWIW, the latter would be preferable for us, largely because it's a pain to keep permissions in sync between GDrive and Outline. But obviously as a small team you have to prioritize carefully, so no worries if it's just not realistic.

**Comment by tommoor** [comment]
> Is the official position that the exiting GDrive and Dropbox integrations handle this functionality sufficiently, or are there plans to expand it further?

It's not, we don't think the embed feature is a replacement for file upload. Ideally we'd support file upload both to Outline storage and optionally to your own cloud storage, this is one of the most upvoted features so It should see priority soon.

**Comment by FeralMib** [comment]
If it helps, I've got a rebased copy of https://github.com/outline/rich-markdown-editor/pull/280 I could push/share? It's still got a few problems (no placeholder link during upload, no mechanism to manage/delete uploads etc) but it's generally working well enough for me.

**Comment by michaelhofer** [comment]
We often have situations where it would be very useful to include PDF in a page. Ideally, they should be uploaded to the Outline storage (similar to images) and shown as preview on the page.

**Comment by nstatrm** [comment]
We are also testing Outline for a few weeks now and we like to migrate an existing wiki to Outline. As we currently have files in some documents we need to migrate them. Currently this is also blocking us.

**Comment by tommoor** [comment]
Progress is being made…

![image](https://user-images.githubusercontent.com/380914/151688019-b657846b-012f-4dcb-8f93-0c9a36959aae.png)

**Comment by nstatrm** [comment]
Thank you for working on the file attachments feature.
I have tested the file attachments feature with the `tom/859-file-attachments` branch. For the first version it's working good, but i have noticed a little bug: While clicking on the link i noticed if i don't click directly on the text, then an empty view is loaded with `https://.../api/attachments.redirect` as the URL. Maybe this bug is because of merging the branch with the current, so please test if you can reproduce it.

![image](https://user-images.githubusercontent.com/98583122/151981861-016d78f6-de6e-4298-9b5b-bba1d1a47b4f.png)

**Comment by tommoor** [comment]
Maybe it is, I cannot reproduce but the mechanics might change yet

**Comment by JustDoItSascha** [comment]
Hey Guys, thanks for the work here? Is there any road map when this feature will be added? I'm keen to use it :)

**Comment by heyValdemar** [comment]
hey guys, I wrote [a detailed guide](https://www.heyvaldemar.com/install-outline-and-keycloak-using-docker-compose/) after I was able to configure Outline with MinIO and Keycloak.

Hopefully, it will help others.
