### ISSUE TITLE
Introduce a concept to nest without requiring a parent document

### ISSUE THREAD

**Issue by tommoor** [outline/outline#933]
Sometimes you want to be able to nest documents but don't have anything to write in the parent category. It would be good to codify this somehow

**Comment by thomasmalley** [comment]
You mean like a folder 📁🙈? This would be awesome since everyone working within a company is going to be used to this Concept. I know there are other ways to categorize data like different kinds of taxonomies, using tags or categories for example. But Folders - even though sometimes looked down upon - have earned their standing by representing Data (documents) in a way that is close to real life and thereby easy to grasp for almost everyone. I had the feeling that ease of use is important to you when looking at your product 👌🏼 Keep up the great work 💪🏼

**Comment by tommoor** [comment]
Note: Parent documents now display an index of their nested child documents by default, so I'm not sure the separate concept is needed any more as it would look identical. 

I do think we could add some help so that users know it's possible to do this though

**Comment by thomasmalley** [comment]
I will check the new Version ASAP
